### ISSUE TITLE
Cannot run command 

### ISSUE THREAD

**Issue by yyx319** [adamtuft/c-kernel#10]
I cannot run the following command 

python3 -m ckernel install AutoCompileKernel autocompile-gcc "Autocompile (gcc)" \   --exe-cflags="-Wl,--no-as-needed" --exe-cxxflags="-Wl,--no-as-needed" --exe-ldflags="-lrt -ldl"

It returns the error:

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
usage: python3 -m ckernel [-h] [-v] action ...
python3 -m ckernel: error: unrecognized arguments: Autocompile (gcc)

**Comment by adamtuft** [comment]
The `install` command accepts 2 positional arguments but you have given 3 (see [positional arguments](https://c-kernel.readthedocs.io/en/latest/00-install.html#positional-arguments) in the docs). This command should work for you:

```
python3 -m ckernel install autocompile-gcc "Autocompile (gcc)" --exe-cflags="-Wl,--no-as-needed" --exe-cxxflags="-Wl,--no-as-needed" --exe-ldflags="-lrt -ldl"
```

**Comment by yyx319** [comment]
It worked. Thanks!
