### ISSUE TITLE
Installation error on Kali linux WSL guest on windows

### ISSUE THREAD

**Issue by meta-forte** [adamtuft/c-kernel#11]
Hi,

OS: Windows 11
Distro: Kali Linux distro on WSL 2
Python: 3.11
nodeJS: 20
g++:13.2

````Shell

Building wheels for collected packages: sysv-ipc
  Building wheel for sysv-ipc (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for sysv-ipc (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      ******************************************************************************
      * Setup can't determine the value of PAGE_SIZE on your system, so it will
      * default to 4096 which may not be correct.
      *
      * Please report this message and your operating system info to the package
      * maintainer listed in the README file.
      ******************************************************************************
      running bdist_wheel
      running build
      running build_ext
      building 'sysv_ipc' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -g -fwrapv -O2 -fPIC -I/home/manas/mypy/include -I/usr/include/python3.11 -c common.c -o build/temp.linux-x86_64-cpython-311/common.o
      common.c:2:10: fatal error: Python.h: No such file or directory
          2 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sysv-ipc
Failed to build sysv-ipc
ERROR: Could not build wheels for sysv-ipc, which is required to install pyproject.toml-based projects
````

**Comment by meta-forte** [comment]
I used random google search suggestion and ran ` sudo apt-get install python-dev-is-python3` 
and reran the installation. This time it did not error out.

However, the kernel is not appearing in the list of available kernels

**Comment by adamtuft** [comment]
Hi @metaforte, thanks for your question. Can you confirm whether the package was successfully installed with:

`python3 -m ckernel --version`

If this works, check the [instructions for installing the kernel](https://c-kernel.readthedocs.io/en/latest/00-install.html#kernel-installation) itself. What happens when you follow these steps?

**Comment by meta-forte** [comment]
I missed this step. Now I see the kernel listed. Is it possible to not mandate file name. Can you generate file name in the code like Cell_01.C, Cell_02.c etc.

**Comment by adamtuft** [comment]
Glad that resolved your issue!

Hmm, I think it would be possible to auto-generate the file name for each cell, however I don't think it would be straightforward to implement. I'm not sure that the benefits would be worth the development effort. Thanks for the suggestion though!
