### ISSUE TITLE
Error about ck_input_wrappers 

### ISSUE THREAD

**Issue by xfliu** [adamtuft/c-kernel#12]
Jupyterlab: ver 4.1.6
c-kernel: ver 0.5.3

A cell with simple hello world c code:
```
////hello.c
#include <stdio.h>

int main(){
    printf("hello, world!\n");
    return 0;
}
```

Below is the error when running the cell:

>  /usr/bin/ld: /tmp/ipython-ckernel-0domji3r/ckernel-input-wrappers.o: in function `ck_setup':
> ck_input_wrappers.c:(.text+0xf9): undefined reference to `dlsym'
> /usr/bin/ld: ck_input_wrappers.c:(.text+0x167): undefined reference to `dlsym'

I add "-ldl" to the kernel.json as follows:

```
{
    "argv": [
        "python3",
        "-m",
        "ckernel",
        "run",
        "-f",
        "{connection_file}"
    ],
    "display_name": "C/C++",
    "env": {
        "CKERNEL_CC": "gcc -ldl",
        "CKERNEL_CXX": "g++ -ldl"
    },
    "interrupt_mode": "message"
}
```

But it is does not work. It seems that the "-ldl" flag should be appended to the end of compile command.

My current solution is to create a new gcc_with_ldl.sh

```
#!/bin/bash
# Wrapper script to add the -ldl flag automatically
gcc "$@" -ldl

```

Here is my question: Is this a bug of c-kernel? Or something wrong with my jupyterlab? Is there any better solution?

**Comment by adamtuft** [comment]
Hi @xfliu thank you for your question! The answer is in the [ckernel FAQs](https://c-kernel.readthedocs.io/en/latest/03-FAQ.html#why-am-i-seeing-errors-like-undefined-reference-to-dlsym) within the documentation.

To solve this you should add `-ldl` to the `--exe-ldflags` option when installing the kernel, or add the magic comment `//% LDFLAGS -ldl` to the code cell.
