### ISSUE TITLE
scanf() inside a loop does not work as expected.

### ISSUE THREAD

**Issue by wangzk** [adamtuft/c-kernel#3]
When the C program use `scanf()` inside a loop to read an array, the scanf() does not work correctly.

For example, for the following program:

```C
#include <stdio.h>
#define INT_ARRAY_LEN 5
int main(void)
{
    int a[INT_ARRAY_LEN] = {0};
    int i = 0;
    printf("input %d numbers:\n", INT_ARRAY_LEN);
    for(i = 0; i < INT_ARRAY_LEN; i++)
    {
        printf("i=%d\n", i);
        scanf("%d", &a[i]);
        printf("get a[i]=%d.\n", a[i]);
    }
    printf("\n");
    return 0;
}
```

When run this program in the Jupyter notebook, it gets:

![2023-10-03_11-31](https://github.com/adamtuft/c-kernel/assets/2674020/2248a51b-d80f-4034-927c-f5b1202c9fa3)

The program should work like the following in a terminal:

![2023-10-03_11-33](https://github.com/adamtuft/c-kernel/assets/2674020/12565fbf-7a54-4dac-be56-f5cf5cdc15f9)

**Comment by adamtuft** [comment]
Thanks for the bug report! This is definitely not working as it should, I'll get it fixed 👍

**Comment by adamtuft** [comment]
@wangzk I've published an update which I believe addresses this issue, please check it out and let me know whether it works for you. To install this from `dev`:

```
git clone -b dev https://github.com/adamtuft/c-kernel.git
pip install --force-reinstall ./c-kernel
```

You shouldn't need to re-install the kernel itself for this update to take effect, just re-start any active kernels you may have. Please let me know whether this update works for you.

Thanks!

**Comment by wangzk** [comment]
It works! Thank you for fixing the bug :)
