### ISSUE TITLE
freopen() still requires interactive input

### ISSUE THREAD

**Issue by wangzk** [adamtuft/c-kernel#8]
If we use freopen() in a program to load the input from a text file, the c-kernel still requires an interactive input at the end of the whole program.

For example, for the following program:

```C
//// debug.c
#include <stdio.h>
int main(void)
{
    char str[255];
    // Use freopen() to redirect the standard input to a text file.
    freopen("input.txt", "r", stdin);
    // Read a string from the file, not keyboard
    scanf("%s", str);
    printf("get a string: %s\n", str);
    return 0;
}
```

Next, prepare a text file `input.txt` with the following content:

```
hello!
```

Run the previous program with the c-kernel. We can see that the c-kernel still requires an input at the end of the program.

![image](https://github.com/adamtuft/c-kernel/assets/2674020/2d285138-509e-4541-ad95-2b449ea94836)

Actually, the program already finishes.

If we compile and run the program in a terminal, the program can finish correctly.

![image](https://github.com/adamtuft/c-kernel/assets/2674020/099b3504-3f04-41aa-8fed-9991f8593195)

**Comment by adamtuft** [comment]
Thanks very much for the bug report! This is caused by c-kernel not recognising the redirection of `stdin` and then still asking the kernel for input when `scanf` is called. I'll get this fixed :+1:

**Comment by adamtuft** [comment]
Hi @wangzk I have published a fix on `dev`. To install it:

```
git clone -b dev https://github.com/adamtuft/c-kernel.git
pip install --force-reinstall ./c-kernel
```

This now gives the expected behaviour when `stdin` is redirected to a file, and then restored to keyboard input afterwards:

```
//// fixed.c
#define _GNU_SOURCE
#define _POSIX_C_SOURCE 1 // for fdopen
#include <stdio.h>
#include <unistd.h>

void restore_stdin(int fd) {
    if (dup2(fd, STDIN_FILENO) == -1) {
        perror("dup2");
    }
    stdin = fdopen(STDIN_FILENO, "r");
    return;
}

int main(void) {
    char str[256] = {0};
    // store copy of stdin fd
    int orig_stdin_fd = dup(fileno(stdin));
    // Use freopen() to redirect the standard input to a text file.
    freopen("input.txt", "r", stdin);
    // Read a string from the file, not keyboard
    scanf("%s", str);
    printf("get a string: %s\n", str);
    // Restore interactive input
    restore_stdin(orig_stdin_fd);
    // Now read a string from keyboard
    scanf("%s", str);
    printf("get a string: %s\n", str);
    return 0;
}
```

This also has the benefit of detecting when `stdin` has been duplicated onto another file descriptor different from `0`, so this code correctly requests interactive input:

```
//// also-fixed.c
#define _GNU_SOURCE
#define _POSIX_C_SOURCE 1 // for fdopen
#include <stdio.h>
#include <unistd.h>

int main(void) {
    char str[256] = {0};
    
    // duplicate stdin with alternative fd
    printf("fileno(stdin)=%d\n", fileno(stdin));
    int alt_stdin_fd = dup(fileno(stdin));
    printf("alt_stdin_fd=%d\n", alt_stdin_fd);
    dup2(fileno(stdin), alt_stdin_fd);
    stdin = fdopen(alt_stdin_fd, "r");
    printf("fileno(stdin)=%d\n", fileno(stdin));

    // Read a string from keyboard
    printf("get input from stdin\n");
    scanf("%s", str);
    printf("get a string: %s\n", str);

    return 0;
}
```

**Comment by wangzk** [comment]
Great! I can confirm in my environment that it solves the problem! Thanks for your efforts :)
