### ISSUE TITLE
TypeError: AutoCompileKernel.autocompile() got an unexpected keyword argument 'cell_meta'

### ISSUE THREAD

**Issue by majiang2018** [adamtuft/c-kernel#9]
`uname -a`
Linux ubuntu2204 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

`python3 --version`
Python 3.10.12

`gcc --version`
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`g++ --version`
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`jupyter notebook --version`
7.0.6

```
pip install ckernel
python3 -m ckernel install ckernel "C/C++"
```

`python3 -m ckernel --version`
0.5.2
`jupyter kernelspec list --json`
```
{
    "ckernel": {
          "resource_dir": "/usr/local/share/jupyter/kernels/ckernel",
          "spec": {
            "argv": [
              "python3",
              "-m",
              "ckernel",
              "run",
              "-f",
              "{connection_file}"
            ],
            "env": {
              "CKERNEL_CC": "gcc",
              "CKERNEL_CXX": "g++"
            },
            "display_name": "C/C++",
            "language": "",
            "interrupt_mode": "message",
            "metadata": {}
          }
    }
}
```

C Code:
```
//// test.cpp
#include <stdio.h>
int main(void){
    printf("hello, world!\n");
    return 0;
}
```
Error Code:
```
 File "/home/ubuntu/.local/lib/python3.10/site-packages/ckernel/autocompile_kernel.py", line 95, in do_execute
    result = await self.autocompile(*args, **kwargs)

TypeError: AutoCompileKernel.autocompile() got an unexpected keyword argument 'cell_meta'
```
@Email:329976764@qq.com

**Comment by pigay** [comment]
Same error on python 3.11.1

**Comment by adamtuft** [comment]
Hi both, thanks very much for this report! I've published a fix to `dev`, I'd be grateful if you could confirm that this fixes the issue for you also:

```
git clone -b dev https://github.com/adamtuft/c-kernel.git
pip install --force-reinstall ./c-kernel
```

**Comment by majiang2018** [comment]
Hi, thank you very much for taking the time to reply to my email. I am confident that this issue has been corrected and I can now use it normally. Wishing you a happy day! My test is as follows:

`//// test.cpp
#include <iostream>
using namespace std;
int main()
{
    cout<<"Hello!";
    return 0;
}
`

wrote file test.cpp
$> g++   test.cpp    -o test
$> ./test 
Hello!

**Comment by pigay** [comment]
Hi, Thanks for the quick fix!

I stumble on undefined reference error (with the exact same program than majiang):

```
/tmp/SLURM_JOB_1935/ipython-ckernel-5xwopftx/ckernel-input-wrappers.o : Dans la fonction « ck_setup » :
ck_input_wrappers.c:(.text+0xdd) : référence indéfinie vers « dlsym »
ck_input_wrappers.c:(.text+0x13e) : référence indéfinie vers « dlsym »
ck_input_wrappers.c:(.text+0x19f) : référence indéfinie vers « dlsym »
ck_input_wrappers.c:(.text+0x200) : référence indéfinie vers « dlsym »
ck_input_wrappers.c:(.text+0x261) : référence indéfinie vers « dlsym »
collect2: error: ld a retourné le statut de sortie 1
```

I suppose this is unrelated to the first problem, though.

Maybe something wrong with my setup?

**Comment by pigay** [comment]
By the way, the cell compiles and executes correctly if I add the following:
```
//% LDFLAGS -ldl
```

Did I miss something in the installation step?

**Comment by adamtuft** [comment]
Hi @pigay that undefined reference is a separate thing, on some setups you need to add an argument when installing the kernel (or a magic command to the cell, as you discovered). See the FAQ's here: https://c-kernel.readthedocs.io/en/latest/03-FAQ.html#id6

**Comment by pigay** [comment]
should have checked the FAQ first. My bad ;)

Works fine now.

Many thanks!
